/**
 * Mobile-First Retention Optimization System
 * Ensures 48px touch targets and mobile performance compliance
 * Research-backed: 70% of users abandon sites with poor mobile UX
 */

import { z } from "zod";

export const TouchTargetSchema = z.object({
  element: z.string(),
  currentSize: z.object({
    width: z.number(),
    height: z.number(),
  }),
  requiredSize: z.object({
    width: z.number().min(48),
    height: z.number().min(48),
  }),
  isCompliant: z.boolean(),
  fixes: z.array(z.string()),
});

export type TouchTarget = z.infer<typeof TouchTargetSchema>;

export const MobileAuditResultSchema = z.object({
  pageUrl: z.string(),
  timestamp: z.date(),
  touchTargets: z.array(TouchTargetSchema),
  performanceMetrics: z.object({
    firstContentfulPaint: z.number(),
    largestContentfulPaint: z.number(),
    cumulativeLayoutShift: z.number(),
    firstInputDelay: z.number(),
    mobileFriendlyScore: z.number(),
  }),
  accessibilityScore: z.number(),
  overallScore: z.number(),
  recommendations: z.array(z.string()),
});

export type MobileAuditResult = z.infer<typeof MobileAuditResultSchema>;

export class MobileRetentionOptimizer {
  private static readonly MINIMUM_TOUCH_SIZE = 48; // 48px WCAG standard
  private static readonly PREFERRED_TOUCH_SIZE = 56; // Preferred for better UX

  static auditTouchTargets(): TouchTarget[] {
    if (typeof window === "undefined") return [];

    const touchElements = document.querySelectorAll(`
      button,
      a,
      input[type="button"],
      input[type="submit"],
      input[type="reset"],
      [role="button"],
      [tabindex="0"],
      .tool-link,
      .mobile-button,
      nav a
    `);

    const results: TouchTarget[] = [];

    touchElements.forEach((element) => {
      const rect = element.getBoundingClientRect();
      const computedStyle = window.getComputedStyle(element);

      // Account for padding in touch target size
      const paddingTop = parseInt(computedStyle.paddingTop);
      const paddingBottom = parseInt(computedStyle.paddingBottom);
      const paddingLeft = parseInt(computedStyle.paddingLeft);
      const paddingRight = parseInt(computedStyle.paddingRight);

      const effectiveWidth = rect.width;
      const effectiveHeight = rect.height;

      const isCompliant =
        effectiveWidth >= this.MINIMUM_TOUCH_SIZE &&
        effectiveHeight >= this.MINIMUM_TOUCH_SIZE;

      const fixes: string[] = [];

      if (effectiveWidth < this.MINIMUM_TOUCH_SIZE) {
        fixes.push(
          `Increase width to minimum ${this.MINIMUM_TOUCH_SIZE}px (current: ${Math.round(effectiveWidth)}px)`
        );
        fixes.push("Apply class: min-w-[48px]");
      }

      if (effectiveHeight < this.MINIMUM_TOUCH_SIZE) {
        fixes.push(
          `Increase height to minimum ${this.MINIMUM_TOUCH_SIZE}px (current: ${Math.round(effectiveHeight)}px)`
        );
        fixes.push("Apply class: min-h-[48px]");
      }

      if (!isCompliant) {
        fixes.push("Add appropriate padding: py-3 px-4");
        fixes.push("Consider using mobile-button or tool-link classes");
      }

      results.push({
        element:
          element.tagName.toLowerCase() +
          (element.className ? `.${element.className.split(" ")[0]}` : ""),
        currentSize: {
          width: Math.round(effectiveWidth),
          height: Math.round(effectiveHeight),
        },
        requiredSize: {
          width: this.MINIMUM_TOUCH_SIZE,
          height: this.MINIMUM_TOUCH_SIZE,
        },
        isCompliant,
        fixes,
      });
    });

    return results;
  }

  static generateMobileCSS(): string {
    return `
/* Mobile-First Retention Optimization CSS */
/* Automatically generated by MobileRetentionOptimizer */

/* Ensure all interactive elements meet 48px minimum */
@media (max-width: 768px) {
  /* Universal touch target base */
  button,
  a[href],
  input[type="button"],
  input[type="submit"],
  input[type="reset"],
  [role="button"],
  [tabindex="0"] {
    min-height: 48px !important;
    min-width: 48px !important;
    padding: 12px 16px !important;
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
  }

  /* Navigation links specific optimizations */
  nav a[href] {
    min-height: 48px !important;
    padding: 12px 16px !important;
    margin: 4px 0 !important;
    border-radius: 8px !important;
    display: flex !important;
    align-items: center !important;
  }

  /* Tool navigation links */
  .tool-link,
  a[href*="/neuroseo"],
  a[href*="/keyword-tool"],
  a[href*="/content-analyzer"],
  a[href*="/competitors"],
  a[href*="/seo-audit"] {
    min-height: 48px !important;
    min-width: 100% !important;
    padding: 12px 16px !important;
    margin: 4px 0 !important;
    touch-action: manipulation !important;
  }

  /* Form inputs */
  input:not([type="checkbox"]):not([type="radio"]),
  select,
  textarea {
    min-height: 48px !important;
    padding: 12px 16px !important;
    font-size: 16px !important; /* Prevents zoom on iOS */
  }

  /* Cards and interactive areas */
  .tool-card,
  .feature-card,
  [role="tabpanel"] > div {
    padding: 16px !important;
    margin: 8px 0 !important;
    min-height: 48px !important;
  }

  /* Dropdown and select elements */
  select {
    appearance: none !important;
    background-image: url("data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTIiIGhlaWdodD0iOCIgdmlld0JveD0iMCAwIDEyIDgiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIGQ9Ik0xIDFMNiA2TDExIDEiIHN0cm9rZT0iIzZCNzI4MCIgc3Ryb2tlLXdpZHRoPSIyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiLz4KPC9zdmc+") !important;
    background-repeat: no-repeat !important;
    background-position: right 12px center !important;
    padding-right: 40px !important;
  }

  /* Checkbox and radio improvements */
  input[type="checkbox"],
  input[type="radio"] {
    min-width: 20px !important;
    min-height: 20px !important;
    margin: 14px !important; /* Centers within 48px touch target */
  }

  /* Icon buttons */
  button[aria-label],
  .icon-button {
    min-width: 48px !important;
    min-height: 48px !important;
    padding: 12px !important;
  }

  /* Modal and dialog close buttons */
  [role="dialog"] button,
  .modal-close {
    min-width: 48px !important;
    min-height: 48px !important;
    padding: 12px !important;
    position: absolute;
    top: 8px;
    right: 8px;
  }

  /* Table actions on mobile */
  table button,
  table a[href] {
    min-width: 44px !important;
    min-height: 44px !important;
    padding: 10px !important;
    margin: 2px !important;
  }
}

/* Additional mobile performance optimizations */
@media (max-width: 768px) {
  /* Reduce animation complexity on mobile */
  * {
    animation-duration: 0.2s !important;
    transition-duration: 0.2s !important;
  }

  /* Optimize font rendering */
  body {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-rendering: optimizeLegibility;
  }

  /* Prevent zoom on input focus (iOS Safari) */
  input,
  select,
  textarea {
    font-size: 16px !important;
  }

  /* Optimize scroll behavior */
  * {
    -webkit-overflow-scrolling: touch;
  }

  /* Reduce layout shifts */
  img,
  video {
    height: auto;
    max-width: 100%;
  }

  /* Optimize tap highlights */
  * {
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1);
    -webkit-user-select: none;
    user-select: none;
  }

  /* Allow text selection where appropriate */
  p,
  span,
  div[contenteditable],
  input,
  textarea {
    -webkit-user-select: text;
    user-select: text;
  }
}

/* High contrast mode support */
@media (prefers-contrast: high) {
  button,
  a[href],
  input {
    border: 2px solid currentColor !important;
  }
}

/* Reduced motion support */
@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
`;
  }

  static runComprehensiveAudit(
    pageUrl: string = window.location.href
  ): MobileAuditResult {
    const touchTargets = this.auditTouchTargets();
    const performanceMetrics = this.measurePerformanceMetrics();
    const accessibilityScore = this.calculateAccessibilityScore();

    const complianceRate =
      touchTargets.length > 0
        ? (touchTargets.filter((t) => t.isCompliant).length /
            touchTargets.length) *
          100
        : 100;

    const overallScore = Math.round(
      (complianceRate +
        accessibilityScore +
        performanceMetrics.mobileFriendlyScore) /
        3
    );

    const recommendations = this.generateRecommendations(
      touchTargets,
      performanceMetrics,
      accessibilityScore
    );

    return {
      pageUrl,
      timestamp: new Date(),
      touchTargets,
      performanceMetrics,
      accessibilityScore,
      overallScore,
      recommendations,
    };
  }

  private static measurePerformanceMetrics() {
    const navigation = performance.getEntriesByType(
      "navigation"
    )[0] as PerformanceNavigationTiming;

    return {
      firstContentfulPaint: this.getMetric("first-contentful-paint") || 0,
      largestContentfulPaint: this.getMetric("largest-contentful-paint") || 0,
      cumulativeLayoutShift: this.getMetric("cumulative-layout-shift") || 0,
      firstInputDelay: this.getMetric("first-input-delay") || 0,
      mobileFriendlyScore: this.calculateMobileFriendlyScore(),
    };
  }

  private static getMetric(name: string): number {
    const entries = performance.getEntriesByName(name);
    return entries.length > 0 ? entries[0].startTime : 0;
  }

  private static calculateMobileFriendlyScore(): number {
    let score = 100;

    // Check viewport meta tag
    const viewport = document.querySelector('meta[name="viewport"]');
    if (
      !viewport ||
      !viewport.getAttribute("content")?.includes("width=device-width")
    ) {
      score -= 20;
    }

    // Check for mobile-unfriendly elements
    const smallText = document.querySelectorAll("*").length;
    let smallTextElements = 0;

    document.querySelectorAll("*").forEach((el) => {
      const style = window.getComputedStyle(el);
      const fontSize = parseInt(style.fontSize);
      if (fontSize < 12) smallTextElements++;
    });

    if (smallTextElements / smallText > 0.1) score -= 15;

    return Math.max(0, score);
  }

  private static calculateAccessibilityScore(): number {
    let score = 100;

    // Check for missing alt attributes
    const images = document.querySelectorAll("img");
    const imagesWithoutAlt = Array.from(images).filter(
      (img) => !img.getAttribute("alt")
    );
    if (imagesWithoutAlt.length > 0) {
      score -= (imagesWithoutAlt.length / images.length) * 20;
    }

    // Check for missing form labels
    const inputs = document.querySelectorAll('input:not([type="hidden"])');
    const inputsWithoutLabels = Array.from(inputs).filter((input) => {
      const id = input.getAttribute("id");
      return (
        !document.querySelector(`label[for="${id}"]`) &&
        !input.getAttribute("aria-label")
      );
    });
    if (inputsWithoutLabels.length > 0) {
      score -= (inputsWithoutLabels.length / inputs.length) * 15;
    }

    // Check for proper heading hierarchy
    const headings = document.querySelectorAll("h1, h2, h3, h4, h5, h6");
    if (headings.length === 0) score -= 10;

    return Math.max(0, score);
  }

  private static generateRecommendations(
    touchTargets: TouchTarget[],
    metrics: any,
    accessibilityScore: number
  ): string[] {
    const recommendations: string[] = [];

    const nonCompliantTargets = touchTargets.filter((t) => !t.isCompliant);
    if (nonCompliantTargets.length > 0) {
      recommendations.push(
        `Fix ${nonCompliantTargets.length} touch targets that don't meet 48px minimum size`
      );
      recommendations.push(
        "Apply mobile-button and tool-link CSS classes for consistency"
      );
    }

    if (metrics.largestContentfulPaint > 2500) {
      recommendations.push(
        "Optimize LCP by reducing image sizes and improving server response times"
      );
    }

    if (metrics.cumulativeLayoutShift > 0.1) {
      recommendations.push(
        "Reduce layout shift by setting explicit dimensions on images and ads"
      );
    }

    if (accessibilityScore < 90) {
      recommendations.push(
        "Improve accessibility by adding alt attributes and form labels"
      );
    }

    if (metrics.mobileFriendlyScore < 95) {
      recommendations.push("Ensure viewport meta tag is properly configured");
      recommendations.push("Increase minimum font size to 12px or larger");
    }

    return recommendations;
  }
}

export const useMobileRetention = () => {
  const runAudit = () => {
    return MobileRetentionOptimizer.runComprehensiveAudit();
  };

  const getTouchTargetStatus = () => {
    const targets = MobileRetentionOptimizer.auditTouchTargets();
    const compliant = targets.filter((t) => t.isCompliant).length;
    const total = targets.length;

    return {
      compliant,
      total,
      percentage: total > 0 ? Math.round((compliant / total) * 100) : 100,
      nonCompliantTargets: targets.filter((t) => !t.isCompliant),
    };
  };

  const generateOptimizedCSS = () => {
    return MobileRetentionOptimizer.generateMobileCSS();
  };

  const applyMobileOptimizations = () => {
    // Apply CSS optimizations dynamically
    const style = document.createElement("style");
    style.textContent = MobileRetentionOptimizer.generateMobileCSS();
    style.id = "mobile-retention-optimizations";

    // Remove existing optimization styles
    const existing = document.getElementById("mobile-retention-optimizations");
    if (existing) {
      existing.remove();
    }

    document.head.appendChild(style);

    return "Mobile retention optimizations applied successfully";
  };

  return {
    runAudit,
    getTouchTargetStatus,
    generateOptimizedCSS,
    applyMobileOptimizations,
  };
};
