name: E2E Tests

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

env:
  NODE_VERSION: "18"
  PLAYWRIGHT_VERSION: "1.37.0"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      # Default value for TEST_BASE_URL
      TEST_BASE_URL: "http://localhost:3000"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Check required secrets
        run: |
          if [[ -z "$OPENAI_API_KEY" ]] || [[ -z "$TEST_USER_EMAIL" ]] || [[ -z "$TEST_USER_PASSWORD" ]]; then
            echo "::error::Required secrets are missing. Please set OPENAI_API_KEY, TEST_USER_EMAIL, and TEST_USER_PASSWORD in repository settings."
            exit 1
          fi
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      - name: Run Playwright tests
        run: npx playwright test
        env:
          # Optional override from secrets
          TEST_BASE_URL: ${{ secrets.TEST_BASE_URL || vars.TEST_BASE_URL || env.TEST_BASE_URL }}
          # Required secrets
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
